version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=11411141
      - DATABASE_NAME=fudytest
      - JWT_SECRET=verysecretKey
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fudytest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11411141
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
